export const teamCodes = {
    "Argentina": "ARG",
    "Australia": "AUS",
    "Belgium": "BEL",
    "Brazil": "BRA",
    "Canada": "CAN",
    "Cameroon": "CMR",
    "Costa Rica": "CRC",
    "Croatia": "CRO",
    "Denmark": "DEN",
    "Ecuador": "ECU",
    "England": "ENG",
    "France": "FRA",
    "Germany": "GER",
    "Ghana": "GHA",
    "Iran": "IRN",
    "Japan": "JPN",
    "South Korea": "KOR",
    "Saudi Arabia": "KSA",
    "Morocco": "MAR",
    "Mexico": "MEX",
    "Netherlands": "NED",
    "Poland": "POL",
    "Portugal": "POR",
    "Qatar": "QAT",
    "Senegal": "SEN",
    "Spain": "SPA",
    "Serbia": "SRB",
    "Switzerland": "SUI",
    "Tunisia": "TUN",
    "Uruguay": "URU",
    "USA": "USA",
    "Wales": "WAL",
    "TBD": "TBD"
}

export const fullNames = {
    "ARG": "Argentina",
    "AUS": "Australia",
    "BEL": "Belgium",
    "BRA": "Brazil",
    "CAN": "Canada",
    "CMR": "Cameroon",
    "CRC": "Costa Rica",
    "CRO": "Croatia",
    "DEN": "Denmark",
    "ECU": "Ecuador",
    "ENG": "England",
    "FRA": "France",
    "GER": "Germany",
    "GHA": "Ghana",
    "IRN": "Iran",
    "JPN": "Japan",
    "KOR": "South Korea",
    "KSA": "Saudi Arabia",
    "MAR": "Morocco",
    "MEX": "Mexico",
    "NED": "Netherlands",
    "POL": "Poland",
    "POR": "Portugal", 
    "QAT": "Qatar",
    "SEN": "Senegal", 
    "SPA": "Spain",
    "SRB": "Serbia" ,
    "SUI": "Switzerland",
    "TUN": "Tunisia",
    "URU": "Uruguay",
    "USA": "USA",
    "WAL": "Wales",
    "TBD": "TBD"
}